# Generated by Django 5.0.6 on 2024-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnai_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
